"use client";

import { useEffect, useState } from "react";
import { addDays, format, isSameDay, parseISO } from "date-fns";
import { Bell, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleUserRound, LayoutDashboard, Plus, Search, Settings, Star, Users, WandSparkles, X, Zap } from "lucide-react";
import { demoAgenda, fixtureFor, footballEntities } from "@/lib/demo-data";
import { getTimingState, getWeekDays, moveWeek, weekLabel } from "@/lib/time";
import type { AgendaItem, FootballEntity, Priority, WorkStatus } from "@/lib/types";

const links = [
  [LayoutDashboard, "Dashboard"], [CalendarDays, "Weekly Calendar"], [Star, "Saved Teams & Players"],
  [CheckCircle2, "Assignments"], [Users, "Workers"], [Bell, "Notifications"], [Settings, "Settings"],
] as const;
const statuses: WorkStatus[] = ["Unassigned", "Assigned", "In Progress", "Ready for Review", "Completed", "Cancelled"];
const priorities: Priority[] = ["Low", "Medium", "High", "Urgent"];

function statusClass(status: WorkStatus) { return status === "In Progress" ? "progress" : status === "Ready for Review" ? "review" : status === "Completed" ? "completed" : ""; }

export function Dashboard() {
  const [anchor, setAnchor] = useState(new Date());
  const [items, setItems] = useState<AgendaItem[]>(() => demoAgenda());
  const [selected, setSelected] = useState<AgendaItem | null>(null);
  const [query, setQuery] = useState("");
  const [mode, setMode] = useState<"club" | "player">("club");
  const [toast, setToast] = useState("");
  const [manualOpen, setManualOpen] = useState(false);
  const days = getWeekDays(anchor);
  const results = query.length >= 2 ? footballEntities.filter((x) => x.type === mode && x.name.toLowerCase().includes(query.toLowerCase())) : [];
  const active = items.filter((x) => !["Completed", "Cancelled"].includes(x.status));
  const warnings = active.filter((x) => getTimingState(x).kind === "warning").length;
  const complete = Math.round((items.filter((x) => x.status === "Completed").length / items.length) * 100);

  useEffect(() => { localStorage.setItem("futonic-agenda", JSON.stringify(items)); }, [items]);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(""), 2600); return () => clearTimeout(id); }, [toast]);

  function update(item: AgendaItem) { setItems((all) => all.map((x) => x.id === item.id ? item : x)); setSelected(item); setToast("Agenda updated successfully"); }
  function addFixture(entity: FootballEntity) { const fixture = fixtureFor(entity); if (items.some((x) => x.id === fixture.id)) return setToast("This fixture is already in your agenda"); setItems((x) => [...x, fixture]); setAnchor(parseISO(fixture.startsAt)); setQuery(""); setToast("Fixture added to the agenda"); }

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="logo-wordmark" role="img" aria-label="Futonic"/></div><nav className="nav">{links.map(([Icon,label],i)=><a href="#" className={i===0?"active":""} key={label} onClick={(e)=>e.preventDefault()}><Icon size={17}/><span>{label}</span></a>)}</nav><div className="sidebar-bottom"><div className="workspace"><div className="avatar">VM</div><div><div style={{fontSize:12,fontWeight:700}}>Vurghun M.</div><div style={{fontSize:10,color:"#d6ccff"}}>Administrator</div></div></div></div></aside>
    <main className="main"><header className="topbar"><div><div className="eyebrow">Creative operations</div><h1>Design Match Agenda</h1></div><div className="top-actions"><span className="date-hide" style={{fontSize:12,color:"#667085",marginRight:7}}>{format(new Date(),"EEEE, MMMM d")}</span><button className="icon-button" aria-label="Notifications"><Bell size={17}/></button><button className="icon-button" aria-label="Profile"><CircleUserRound size={19}/></button></div></header>
      <div className="content"><section className="overview"><div className="welcome"><div className="eyebrow" style={{color:"#b9ef35"}}>Good evening, Vurghun</div><h2>Your week is looking sharp.</h2><p>{active.length} active design jobs · {warnings} need attention in the next 48 hours.</p></div><Metric label="Active jobs" value={String(active.length)} note="Across this agenda"/><Metric label="Due in 48h" value={String(warnings)} note="Needs attention"/><Metric label="Completion" value={`${complete}%`} note="This schedule"/></section>
      <section className="search-panel"><div className="search-row"><div className="search-box"><Search size={17}/><input aria-label="Search football" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={`Search ${mode === "club" ? "clubs" : "players"} — try “Real” or “Saka”`}/></div><div className="segmented"><button className={mode==="club"?"active":""} onClick={()=>setMode("club")}>Clubs</button><button className={mode==="player"?"active":""} onClick={()=>setMode("player")}>Players</button></div><button className="button primary" onClick={()=>setManualOpen(true)}><Plus size={16}/> Manual item</button></div>{query.length>=2&&<div className="results">{results.length?results.map((r)=><button className="result" key={r.id} onClick={()=>addFixture(r)}><div className="crest">{r.crest}</div><div><strong>{r.name}</strong><small>{r.subtitle}{r.club?` · ${r.club}`:""}</small></div><Plus size={15} style={{marginLeft:"auto"}}/></button>):<div style={{padding:12,color:"#667085",fontSize:13}}>No {mode}s found. Try another name.</div>}</div>}</section>
      <section className="calendar-card"><div className="calendar-head"><div><h2>Weekly schedule</h2><p>{weekLabel(anchor)} · Asia/Baku (UTC+4)</p></div><div className="week-controls"><button className="button" aria-label="Previous week" onClick={()=>setAnchor(moveWeek(anchor,-1))}><ChevronLeft size={15}/></button><button className="button" onClick={()=>setAnchor(new Date())}>Today</button><button className="button" aria-label="Next week" onClick={()=>setAnchor(moveWeek(anchor,1))}><ChevronRight size={15}/></button></div></div><div className="calendar-grid">{days.map((day)=><Day key={day.toISOString()} day={day} items={items.filter((x)=>isSameDay(parseISO(x.startsAt),day))} onSelect={setSelected}/>)}</div></section></div>
    </main>{selected&&<Details item={selected} onClose={()=>setSelected(null)} onSave={update} onRemove={(id)=>{setItems(x=>x.filter(i=>i.id!==id));setSelected(null);setToast("Item removed")}}/>}{manualOpen&&<ManualModal onClose={()=>setManualOpen(false)} onAdd={(item)=>{setItems(x=>[...x,item]);setAnchor(parseISO(item.startsAt));setManualOpen(false);setToast("Manual item created")}}/>}{toast&&<div className="toast"><CheckCircle2 size={15} style={{display:"inline",marginRight:8,color:"#b9ef35"}}/>{toast}</div>}</div>;
}

function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><span>{note}</span></div>}

function Day({day,items,onSelect}:{day:Date;items:AgendaItem[];onSelect:(x:AgendaItem)=>void}){const today=isSameDay(day,new Date());return <div className={`day ${today?"today":""}`}><div className="day-head"><span className="day-name">{format(day,"EEE")}</span><span className="day-number">{format(day,"d")}</span></div><div className="day-body">{items.length?items.sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).map((item)=><MatchCard item={item} key={item.id} onClick={()=>onSelect(item)}/>):<div className="empty">No assignments</div>}</div></div>}

function MatchCard({item,onClick}:{item:AgendaItem;onClick:()=>void}){const timing=getTimingState(item);return <button className={`match-card ${timing.kind} ${item.kind}`} onClick={onClick}><div className="match-top"><b>{format(parseISO(item.startsAt),"HH:mm")}</b>{timing.label&&<span className="warning-label"><Zap size={10}/>{timing.label}</span>}</div>{item.kind==="fixture"?<><div className="player-focus"><CircleUserRound size={13}/><span>{item.selectedPlayer||"Player not selected"}</span></div><div className="teams"><div className="team"><span className="mini">{item.homeCode}</span>{item.home}</div><div className="team"><span className="mini">{item.awayCode}</span>{item.away}</div></div></>:<div className="manual-title"><WandSparkles size={13} style={{display:"inline",marginRight:6,color:"#2e08cf"}}/>{item.title}</div>}<div className="competition">{item.competition}</div><div className="card-foot"><span className={`badge ${statusClass(item.status)}`}>{item.status}</span><span className="priority">{item.priority}</span></div></button>}

function Details({item,onClose,onSave,onRemove}:{item:AgendaItem;onClose:()=>void;onSave:(x:AgendaItem)=>void;onRemove:(id:string)=>void}){const [draft,setDraft]=useState(item);return <div className="backdrop" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose()}}><aside className="drawer" role="dialog" aria-modal="true" aria-label="Match details"><div className="drawer-head"><div><div className="eyebrow">{item.kind==="fixture"?item.competition:"Manual agenda item"}</div><h2>{item.kind==="fixture"?"Player assignment":item.title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18}/></button></div>{item.kind==="fixture"&&<><div className="featured-player"><CircleUserRound size={22}/><div><span>Featured player</span><strong>{item.selectedPlayer||"Not selected"}</strong></div></div><div className="versus"><div><div className="big-crest">{item.homeCode}</div><strong>{item.home}</strong></div><div className="vs">VS</div><div><div className="big-crest">{item.awayCode}</div><strong>{item.away}</strong></div></div></>}<div className="detail-grid"><div className="detail"><span>Kickoff</span><strong>{format(parseISO(item.startsAt),"EEE, MMM d · HH:mm")}</strong></div><div className="detail"><span>Venue</span><strong>{item.venue||"Not available"}</strong></div><div className="detail"><span>Competition</span><strong>{item.competition||"Manual"}</strong></div><div className="detail"><span>Round</span><strong>{item.round||"—"}</strong></div></div><div className="two-col"><Field label="Assigned worker"><select value={draft.worker||""} onChange={e=>setDraft({...draft,worker:e.target.value,status:draft.status==="Unassigned"?"Assigned":draft.status})}><option value="">Unassigned</option><option>Imran M.</option><option>Aydin K.</option></select></Field><Field label="Work status"><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as WorkStatus})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Priority"><select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value as Priority})}>{priorities.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Internal notes"><textarea value={draft.notes||""} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="Creative direction, references, deliverables…"/></Field><div className="drawer-actions"><button className="button" onClick={()=>confirm("Remove this item from the agenda?")&&onRemove(item.id)}>Remove</button><button className="button accent" onClick={()=>onSave(draft)}>Save changes</button></div></aside></div>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="form-row"><label>{label}</label>{children}</div>}

function ManualModal({onClose,onAdd}:{onClose:()=>void;onAdd:(x:AgendaItem)=>void}){const tomorrow=format(addDays(new Date(),1),"yyyy-MM-dd'T'15:00");const [title,setTitle]=useState("");const [starts,setStarts]=useState(tomorrow);return <div className="backdrop"><aside className="drawer" role="dialog" aria-modal="true"><div className="drawer-head"><div><div className="eyebrow">New creative task</div><h2>Add manual item</h2></div><button className="icon-button" onClick={onClose}><X size={18}/></button></div><Field label="Title"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Derby day carousel" autoFocus/></Field><Field label="Date and time"><input type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)}/></Field><Field label="Work type"><select><option>Social media design</option><option>Match poster</option><option>Brand asset</option><option>Video thumbnail</option></select></Field><div className="two-col"><Field label="Worker"><select><option>Imran M.</option><option>Aydin K.</option></select></Field><Field label="Priority"><select><option>Medium</option><option>High</option><option>Urgent</option><option>Low</option></select></Field></div><Field label="Description"><textarea placeholder="Add deliverables or creative direction…"/></Field><div className="drawer-actions"><button className="button" onClick={onClose}>Cancel</button><button className="button accent" disabled={!title.trim()} onClick={()=>onAdd({id:`manual-${Date.now()}`,kind:"manual",title,startsAt:new Date(starts).toISOString(),competition:"Manual creative work",worker:"Imran M.",status:"Assigned",priority:"Medium"})}>Create item</button></div></aside></div>}
